-- Identifying the original tables data types


USE WideWorldImporters 


SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'Countries'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'StateProvinces'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'Cities'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'CustomerCategories'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'BuyingGroups'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'People'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'Customers'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'DeliveryMethods'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'TransactionTypes'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'PaymentMethods'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'StockGroups'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'Colors'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'SupplierCategories'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'Suppliers'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'StockItems'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'SpecialDeals'


SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'CustomerTransactions'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'Orders'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'Invoices'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'OrderLines'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'InvoiceLines'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'StockitemHoldings'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'PurchaseOrderLines'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'PurchaseOrders'

SELECT	*
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'SupplierTransactions'



